import React, { useState, useEffect } from 'react';
import { AddressModel } from '../../models/AddressModel';
import { Dialog, DialogTitle, DialogContent, DialogActions, TextField, Button, Box } from '@mui/material';

const AddressDialog = ({ open, onClose, onSave, initialAddress }) => {
    const [calle, setCalle] = useState('');
    const [numero, setNumero] = useState('');
    const [departamento, setDepartamento] = useState('');
    const [localidad, setLocalidad] = useState('');

    useEffect(() => {
        if (open) {
            setCalle(initialAddress?.calle || '');
            setNumero(initialAddress?.numero || '');
            setDepartamento(initialAddress?.departamento || '');
            setLocalidad(initialAddress?.localidad || '');
        }
    }, [open, initialAddress]);

    if (!open) return null;

    const handleSave = () => {
        const address = new AddressModel(
            initialAddress?.id || null, // ID will be generated by saving function if null
            calle.trim(),
            numero.trim(),
            departamento.trim() || null,
            localidad.trim()
        );
        onSave(address);
        onClose();
    };

    const isFormValid = calle.trim() !== '' && localidad.trim() !== '';

    return (
        <Dialog open={open} onClose={onClose} maxWidth="sm" fullWidth>
            <DialogTitle>Dirección</DialogTitle>
            <DialogContent>
                <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2, mt: 1 }}>
                    <TextField
                        fullWidth
                        label="Calle"
                        value={calle}
                        onChange={(e) => setCalle(e.target.value)}
                        required
                    />
                    <TextField
                        fullWidth
                        label="Número"
                        value={numero}
                        onChange={(e) => setNumero(e.target.value)}
                    />
                    <TextField
                        fullWidth
                        label="Departamento (Opcional)"
                        value={departamento}
                        onChange={(e) => setDepartamento(e.target.value)}
                    />
                    <TextField
                        fullWidth
                        label="Localidad"
                        value={localidad}
                        onChange={(e) => setLocalidad(e.target.value)}
                        required
                    />
                </Box>
            </DialogContent>
            <DialogActions>
                <Button onClick={onClose} color="inherit">
                    Cancelar
                </Button>
                <Button onClick={handleSave} variant="contained" disabled={!isFormValid}>
                    Guardar
                </Button>
            </DialogActions>
        </Dialog>
    );
};

export default AddressDialog;
